# Generated by Django 5.0 on 2024-02-06 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('514aad22-59ae-4c7b-a3b6-7d96247a7a7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
